import type { NavSection } from './types';

export const NAV: NavSection[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    u: 'ڈیش بورڈ',
    icon: 'home',
    group: 'Main',
    tabs: [
      { id: 'home', label: 'Home' },
      { id: 'overview', label: 'Graphs & comparison' },
      { id: 'alerts', label: 'Alerts' },
    ],
  },
  {
    id: 'tasks',
    label: 'Tasks',
    u: 'کام',
    icon: 'ok',
    group: 'Main',
    tabs: [
      { id: 'list', label: 'Tasks' },
      { id: 'projects', label: 'Projects' },
      { id: 'summary', label: 'Summary' },
    ],
  },
  {
    id: 'properties',
    label: 'Properties',
    u: 'جائیدادیں',
    icon: 'grid',
    group: 'Operations',
    tabs: [
      { id: 'inventory', label: 'Inventory' },
      { id: 'purchases', label: 'Purchase register', need: 'purchases' },
      { id: 'performance', label: 'Performance' },
      { id: 'projects', label: 'Projects' },
    ],
  },
  {
    id: 'trading',
    label: 'Cost Sheets',
    u: 'لاگت شیٹ و ٹریڈنگ',
    icon: 'calculator',
    group: 'Operations',
    tabs: [
      { id: 'sheets', label: 'Cost sheet register' },
      { id: 'calculator', label: 'Cost sheet' },
      { id: 'mirrors', label: 'Mirror cost sheets' },
      { id: 'analytics', label: 'Trading analytics' },
    ],
  },
  {
    id: 'sales',
    label: 'Sales',
    u: 'فروخت',
    icon: 'tag',
    group: 'Operations',
    tabs: [
      { id: 'register', label: 'Sales register' },
      { id: 'proformaInvoices', label: 'Proforma invoices' },
      { id: 'saleInvoices', label: 'Sale invoices' },
      { id: 'purchaseInvoices', label: 'Purchase invoices' },
      { id: 'mirrorSaleInvoices', label: 'Mirror sale invoices' },
      { id: 'mirrorPurchaseInvoices', label: 'Mirror purchase invoices' },
      { id: 'receivables', label: 'Receivables', need: 'receivables' },
    ],
  },
  {
    id: 'agents',
    label: 'Agents',
    u: 'ایجنٹ',
    icon: 'users',
    group: 'Operations',
    tabs: [
      { id: 'directory', label: 'Agent directory', need: 'agents' },
      { id: 'commissions', label: 'Commissions' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    u: 'مالیات',
    icon: 'chart',
    group: 'Finance',
    tabs: [
      { id: 'pnl', label: 'Profit & loss', need: 'pnl' },
      { id: 'profit', label: 'Profit tracking', need: 'profit' },
      { id: 'cashflow', label: 'Cash flow', need: 'cashflow' },
      { id: 'payables', label: 'Payables', need: 'payables' },
      { id: 'assets', label: 'Assets', need: 'pnl' },
    ],
  },
  {
    id: 'costs',
    label: 'Costs',
    u: 'اخراجات',
    icon: 'wallet',
    group: 'Finance',
    tabs: [
      { id: 'expenses', label: 'Expenses', need: 'expenses' },
      { id: 'salaries', label: 'Salaries', need: 'salaries' },
      { id: 'bills', label: 'Bills', need: 'bills' },
      { id: 'tax', label: 'Tax', need: 'tax' },
      { id: 'zakat', label: 'Zakat', need: 'zakat' },
      { id: 'charity', label: 'Charity' },
    ],
  },
  {
    id: 'admin',
    label: 'Admin',
    u: 'انتظام',
    icon: 'shield',
    group: 'System',
    tabs: [
      { id: 'transactions', label: 'Transactions', need: 'transactions' },
      { id: 'audit', label: 'Audit trail', need: 'audit' },
      { id: 'users', label: 'Admin account' },
    ],
  },
];

export const PAGE_META: Record<string, { t: string; u?: string; p?: string }> = {
  'dashboard/home': { t: 'Home', u: 'ہوم' },
  'tasks/list': { t: 'Tasks', u: 'کام', p: 'Everything that needs doing, by project, status and priority.' },
  'tasks/projects': { t: 'Projects', u: 'پراجیکٹس', p: 'Groups of tasks and how far each one has got.' },
  'tasks/summary': { t: 'Project summary', u: 'خلاصہ', p: 'Completion, overdue work and tasks per project.' },
  'dashboard/overview': { t: 'Dashboard', u: 'ڈیش بورڈ' },
  'dashboard/alerts': { t: 'Alerts & notifications', u: 'اطلاعات', p: 'Everything that needs a decision, most urgent first.' },
  'properties/inventory': { t: 'Property inventory', u: 'اسٹاک و مالیت', p: 'Unsold stock: what it cost, what it is worth today, and the difference.' },
  'properties/purchases': { t: 'Purchase register', u: 'خرید رجسٹر', p: 'Every property bought, with acquisition costs and what is still owed to the seller.' },
  'properties/performance': { t: 'Property performance', u: 'جائیداد کارکردگی', p: 'Profit on each property sold, after acquisition costs, commission, tax and selling costs.' },
  'properties/projects': { t: 'Projects', u: 'منصوبے', p: 'Every project / society: stock held, what it cost, what it is worth, and what has been sold.' },
  'trading/sheets': { t: 'Cost sheet register', u: 'لاگت رجسٹر', p: 'Complete trading ledger: acquisition cost basis, sale realization, brokerage, statutory taxes, and net margins.' },
  'trading/calculator': { t: 'Cost sheet', u: 'لاگت شیٹ', p: 'One deal: purchase price, selling costs, gross profit and net margin, read from the records.' },
  'trading/mirrors': { t: 'Mirror cost sheets', u: 'نقل لاگت شیٹ', p: 'Editable copies of cost sheets, kept apart from the real deals. They never change a property or the trading figures.' },
  'trading/analytics': { t: 'Trading analytics', u: 'تجزیہ منافع', p: 'Portfolio-level trading velocity, capital turnover, tax-to-profit ratios, and realized margin breakdown.' },
  'sales/register': { t: 'Sales register', u: 'فروخت رجسٹر', p: 'Every sale with buyer, agent, amount received and amount outstanding.' },
  'sales/proformaInvoices': { t: 'Proforma invoices', u: 'پروفارما انوائس', p: 'Quotations given to buyers before a sale. A proforma is not a receipt and moves no money.' },
  'sales/saleInvoices': { t: 'Sale invoices', u: 'فروخت رسید', p: 'Invoices given to buyers — receipt of sale with all transaction details.' },
  'sales/purchaseInvoices': { t: 'Purchase invoices', u: 'خرید رسید', p: 'Invoices kept by the company — internal purchase receipts for record keeping.' },
  'sales/mirrorSaleInvoices': { t: 'Mirror sale invoices', u: 'نقل فروخت رسید', p: 'Editable copies of sale invoices, numbered in a series of their own. Changing a mirror never changes the original.' },
  'sales/mirrorPurchaseInvoices': { t: 'Mirror purchase invoices', u: 'نقل خرید رسید', p: 'Editable copies of purchase invoices, numbered in a series of their own. Changing a mirror never changes the original.' },
  'sales/receivables': { t: 'Accounts receivable', u: 'واجب الوصول', p: 'What customers still owe, and how far past due each balance is.' },
  'agents/directory': { t: 'Agent directory', u: 'ایجنٹ', p: 'Sales, profit generated and commission for every agent in the period.' },
  'agents/commissions': { t: 'Commission ledger', u: 'کمیشن کھاتہ', p: 'What each agent earned, what has been paid, and what is still owed.' },
  'finance/pnl': { t: 'Profit & loss', u: 'نفع و نقصان', p: 'The full statement for the selected period, revenue down to net profit.' },
  'finance/profit': { t: 'Profit tracking', u: 'منافع', p: 'Purchases, sales, gross profit, expenses and net profit by week, month or year.' },
  'finance/cashflow': { t: 'Cash flow', u: 'نقدی بہاؤ', p: 'Money received and paid, with opening and closing balance.' },
  'finance/payables': { t: 'Accounts payable', u: 'واجب الادا', p: 'What the company owes sellers, agents, staff, vendors and the tax authority.' },
  'finance/assets': { t: 'Assets', u: 'اثاثے', p: 'Things the company bought to keep — furniture, computers, vehicles. Recorded as assets, so they are not charged against profit.' },
  'costs/expenses': { t: 'Expenses', u: 'اخراجات', p: 'Office, personal and other expenses by category and vendor, with anything still unpaid. Assets are kept under Finance → Assets.' },
  'costs/salaries': { t: 'Employee salaries', u: 'تنخواہیں', p: 'Basic, bonus, allowance and deductions per employee.' },
  'costs/bills': { t: 'Bills', u: 'بل', p: 'Recurring and one-off bills, their due dates and anything overdue.' },
  'costs/tax': { t: 'Tax', u: 'ٹیکس', p: 'All tax obligations, split between transaction withholding tax and corporate income tax.' },
  'costs/zakat': { t: 'Zakat', u: 'زکوٰۃ', p: 'Zakat calculated, paid and remaining — reported separately from operating expenses.' },
  'costs/charity': { t: 'Charity', u: 'خیرات', p: 'Charity and donations given — from deal cost sheets and from the expense ledger.' },
  'admin/transactions': { t: 'Transaction ledger', u: 'لین دین کھاتہ', p: 'Every financial transaction with reference, method, account and approver.' },
  'admin/audit': { t: 'Audit trail', u: 'آڈٹ', p: 'Who did what, and when. Records are voided or reversed, never deleted.' },
  'admin/users': { t: 'Admin account', u: 'ایڈمن اکاؤنٹ', p: 'This portal has a single administrator account with full access.' },
  'account': { t: 'My account', u: 'میرا اکاؤنٹ' },
  'appearance': { t: 'Appearance', u: 'ظاہری شکل' },
  'search': { t: 'Search results', u: 'تلاش' },
};

export const SC = ['var(--s1)', 'var(--s2)', 'var(--s3)', 'var(--s4)', 'var(--s5)', 'var(--s6)'];
export const OC = ['var(--o1)', 'var(--o2)', 'var(--o3)', 'var(--o4)'];
